
ccflags-y += -I$(srctree)/drivers/input/touchscreen/zte_touchscreen/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/zte_touchscreen/focaltech_touch_v3/firmware_config/$(CONFIG_TS_FIRMWARE)/
obj-$(CONFIG_TOUCHSCREEN_FTS_V3) += focaltech_test.o
obj-$(CONFIG_TOUCHSCREEN_FTS_V3) += focaltech_test_ini.o
obj-$(CONFIG_TOUCHSCREEN_FTS_V3) += supported_ic/
